name: Laravel CI/CD

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: payment_system_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug
        tools: composer:v2

    - uses: actions/checkout@v3

    - name: Debug Repository Structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Directory content:"
        ls -la
        find . -name "artisan" -type f | xargs echo "Artisan file found at:"
        find . -name "composer.json" -type f | xargs echo "composer.json found at:"

    - name: Copy .env if exists
      run: |
        if [ -f ".env.example" ]; then
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          echo ".env file created from .env.example"
        else
          echo ".env.example not found"
          echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=payment_system_test" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=password" >> .env
          echo "Basic .env file created"
        fi

    - name: Find and Install Dependencies
      run: |
        if [ -f "composer.json" ]; then
          composer install --prefer-dist --no-interaction --no-progress
          echo "Dependencies installed from root composer.json"
        else
          COMPOSER_JSON=$(find . -name "composer.json" -not -path "*/vendor/*" | head -n 1)
          if [ -n "$COMPOSER_JSON" ]; then
            COMPOSER_DIR=$(dirname "$COMPOSER_JSON")
            echo "Found composer.json at: $COMPOSER_DIR"
            cd "$COMPOSER_DIR"
            composer install --prefer-dist --no-interaction --no-progress
            echo "Dependencies installed from found composer.json"
          else
            echo "No composer.json found in repository"
            exit 1
          fi
        fi

    - name: Check and Generate Artisan Key
      run: |
        ARTISAN_FILE=$(find . -name "artisan" -type f | head -n 1)
        if [ -n "$ARTISAN_FILE" ]; then
          ARTISAN_DIR=$(dirname "$ARTISAN_FILE")
          echo "Found artisan at: $ARTISAN_DIR"
          cd "$ARTISAN_DIR"
          php artisan key:generate --force
          echo "App key generated"
        else
          echo "Artisan file not found, skipping key generation"
        fi

    - name: Set Directory Permissions if Needed
      run: |
        ARTISAN_FILE=$(find . -name "artisan" -type f | head -n 1)
        if [ -n "$ARTISAN_FILE" ]; then
          ARTISAN_DIR=$(dirname "$ARTISAN_FILE")
          cd "$ARTISAN_DIR"
          if [ -d "storage" ] && [ -d "bootstrap/cache" ]; then
            chmod -R 777 storage bootstrap/cache
            echo "Directory permissions set"
          fi
        fi

    - name: Run Database Migrations if Artisan Exists
      run: |
        ARTISAN_FILE=$(find . -name "artisan" -type f | head -n 1)
        if [ -n "$ARTISAN_FILE" ]; then
          ARTISAN_DIR=$(dirname "$ARTISAN_FILE")
          cd "$ARTISAN_DIR"
          php artisan config:clear
          php artisan migrate --force || echo "Migration failed, but continuing..."
          echo "Database configuration completed"
        fi

    - name: Run Tests if PHPUnit Exists
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: payment_system_test
        DB_USERNAME: root
        DB_PASSWORD: password
      run: |
        if [ -f "vendor/bin/phpunit" ]; then
          vendor/bin/phpunit --coverage-clover=coverage.xml
          echo "Tests executed at root level"
        else
          PHPUNIT=$(find . -path "*/vendor/bin/phpunit" | head -n 1)
          if [ -n "$PHPUNIT" ]; then
            PHPUNIT_DIR=$(dirname $(dirname $(dirname "$PHPUNIT")))
            echo "Found PHPUnit at: $PHPUNIT_DIR"
            cd "$PHPUNIT_DIR"
            vendor/bin/phpunit --coverage-clover=coverage.xml
            echo "Tests executed from found location"
          else
            echo "PHPUnit not found, skipping tests"
          fi
        fi

    - name: Upload Coverage Report if Available
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

  laravel-deploy:
    needs: laravel-tests
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        cat >>~/.ssh/config <<END
        Host production
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/deploy_key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}

    - name: Determine Project Structure and Deploy
      run: |
        # Find Laravel project root directory
        ARTISAN_FILE=$(find . -name "artisan" -type f | head -n 1)
        if [ -n "$ARTISAN_FILE" ]; then
          LARAVEL_DIR=$(dirname "$ARTISAN_FILE")
          echo "Found Laravel project at: $LARAVEL_DIR"
          RELATIVE_PATH=$(realpath --relative-to="$(pwd)" "$LARAVEL_DIR")
          
          if [ "$RELATIVE_PATH" = "." ]; then
            # Laravel is at repository root
            ssh production 'cd /var/www/payment-system && git pull origin main && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache'
          else
            # Laravel is in a subdirectory
            ssh production "cd /var/www/payment-system && git pull origin main && cd $RELATIVE_PATH && composer install --no-interaction --prefer-dist --optimize-autoloader && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"
          fi
        else
          echo "Laravel project not found, cannot deploy"
          exit 1
        fi
